import 'package:khunt_parivar_mataji_madh/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.areYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  AppStrings.no: "No",
  AppStrings.yesExit: "Yes, exit",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.hello: "Hello ",
  AppStrings.noDataFound: "No data found",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "Log Out",
  AppStrings.username: "Username",
  AppStrings.enterUsername: "Enter username",
  AppStrings.pleaseEnterUserName: "Please enter username",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password",
  AppStrings.createReceipt: "Create Receipt",
  AppStrings.receiptHistory: "Receipt History",
  AppStrings.successfullyDownloadedAtDownloadFolder: "Successfully downloaded at 'Download' folder.",
  AppStrings.downloadFailedPleaseTryAgain: "Download failed, Please try again.",
  AppStrings.update: 'Update',
  AppStrings.newVersionAvailable: 'A new version is available. Please upgrade to it.',
  AppStrings.charity: "Charity",
  AppStrings.expense: "Expense",
  AppStrings.save: "Save",
  AppStrings.personName: "Person name",
  AppStrings.enterPersonName: "Enter person name",
  AppStrings.pleaseEnterPersonName: "Please enter person name",
  AppStrings.pleaseEnterAmount: "Please enter amount",
  AppStrings.amountMustBeNumericOnly: "Amount must be numeric only",
  AppStrings.phoneNumber: "Phone number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number",
  AppStrings.address: "Address",
  AppStrings.enterAddress: "Enter address",
  AppStrings.pleaseEnterAddress: "Please enter address",
  AppStrings.cash: "Cash",
  AppStrings.cheque: "Cheque",
  AppStrings.chequeNumber: "Cheque number",
  AppStrings.enterChequeNumber: "Enter cheque number",
  AppStrings.pleaseEnterChequeNumber: "Please enter cheque number",
  AppStrings.expenseName: "Expense name",
  AppStrings.enterExpenseName: "Enter expense name",
  AppStrings.pleaseEnterExpenseName: "Please enter expense name",
  AppStrings.expenseNote: "Expense note",
  AppStrings.enterExpenseNote: "Enter expense note",
  AppStrings.pleaseEnterExpenseNote: "Please enter expense note",
  AppStrings.expenseDate: "Expense date",
  AppStrings.selectExpenseDate: "Select expense date",
  AppStrings.pleaseSelectExpenseDate: "Please select expense date",
  AppStrings.viewReceipt: "View receipt",
  AppStrings.whatsappNotInstalled: "Whatsapp not installed",
  AppStrings.searchName: "Search name",
  AppStrings.date: "Date",
  AppStrings.amount: "Amount",
};
