import 'package:khunt_parivar_mataji_madh/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: "લૉગ આઉટ",
  AppStrings.username: "વપરાશકર્તા નામ",
  AppStrings.enterUsername: "વપરાશકર્તા નામ દાખલ કરો",
  AppStrings.pleaseEnterUserName: "કૃપા કરીને વપરાશકર્તા નામ દાખલ કરો",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો",
  AppStrings.createReceipt: "રસીદ બનાવો",
  AppStrings.receiptHistory: "ફાળો",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' ફોલ્ડર પર સફળતાપૂર્વક ડાઉનલોડ કર્યું.",
  AppStrings.downloadFailedPleaseTryAgain: "ડાઉનલોડ નિષ્ફળ થયું, કૃપા કરીને ફરી પ્રયાસ કરો.",
  AppStrings.update: "અપડેટ કરો",
  AppStrings.newVersionAvailable: "નવું સંસ્કરણ ઉપલબ્ધ છે. કૃપા કરીને તેમાં અપગ્રેડ કરો.",
  AppStrings.charity: "ફાળો",
  AppStrings.expense: "ખર્ચ",
  AppStrings.save: "સેવ",
  AppStrings.personName: "વ્યક્તિ નામ",
  AppStrings.enterPersonName: "વ્યક્તિ નામ દાખલ કરો",
  AppStrings.pleaseEnterPersonName: "કૃપા કરીને વ્યક્તિ નામ દાખલ કરો",
  AppStrings.pleaseEnterAmount: "કૃપા કરીને રકમ દાખલ કરો",
  AppStrings.amountMustBeNumericOnly: "રકમ માત્ર આંકડાકીય હોવી જોઈએ",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો",
  AppStrings.address: "સરનામું",
  AppStrings.enterAddress: "સરનામું દાખલ કરો",
  AppStrings.pleaseEnterAddress: "કૃપા કરીને સરનામું દાખલ કરો",
};
