import 'package:khunt_parivar_mataji_madh/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.hello: "नमस्ते ",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.username: "उपयोगकर्ता नाम",
  AppStrings.enterUsername: "उपयोगकर्ता नाम दर्ज करें",
  AppStrings.pleaseEnterUserName: "कृपया उपयोक्तानाम दर्ज करें",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पासवर्ड दर्ज करे",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें",
  AppStrings.createReceipt: "रसीद बनाएं",
  AppStrings.receiptHistory: "रसीद की यादी",
  AppStrings.successfullyDownloadedAtDownloadFolder: "'Download' फ़ोल्डर में सफलतापूर्वक डाउनलोड किया गया।",
  AppStrings.downloadFailedPleaseTryAgain: "डाउनलोड विफल, कृपया पुनः प्रयास करें।",
  AppStrings.update: "अद्यतन",
  AppStrings.newVersionAvailable: "एक नया संस्करण उपलब्ध है। कृपया इसे अपग्रेड करें।",
  AppStrings.charity: "योगदान",
  AppStrings.expense: "व्यय",
  AppStrings.save: "सेव",
  AppStrings.personName: "व्यक्ति का नाम",
  AppStrings.enterPersonName: "व्यक्ति का नाम दर्ज करें",
  AppStrings.pleaseEnterPersonName: "कृपया व्यक्ति का नाम दर्ज करें",
  AppStrings.pleaseEnterAmount: "कृपया व्यक्ति का नाम दर्ज करें",
  AppStrings.amountMustBeNumericOnly: "राशि केवल संख्यात्मक होनी चाहिए",
  AppStrings.phoneNumber: "फ़ोन नंबर",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज",
  AppStrings.pleaseEnterValidPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें",
  AppStrings.address: "पता",
  AppStrings.enterAddress: "पता दर्ज करें",
  AppStrings.pleaseEnterAddress: "कृपया पता दर्ज करें",
};
